### ISSUE TITLE
Gulpicon won't generate any css files or preview.html

### ISSUE THREAD

**Issue by varisvitols** [filamentgroup/gulpicon#14]
I am using default configuration, but I won't get any CSS files or preview.html. PNG files are generated just fine, also the script is included as it should be. AM I missing something?

**Comment by kaanra** [comment]
This is 2 years past the original question, but hope this is helpful to anyone running into this issue.

You must include the `default-css.hbs`, `preview-custom.hbs`, and `preview.hbs` like shown in the example at https://github.com/filamentgroup/gulpicon/tree/master/example. Otherwise, the CSS and preview.html will not generate.
